printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
quoteProps: consistent
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
proseWrap: preserve
endOfLine: lf
